import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { getDirection, resolveLocale } from '@/lib/i18n/resolve-locale'
import '@/app/globals.css'
import { ThemeScript } from '@/components/ui/theme-toggle/theme-script'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function Layout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Promise<{ locale: string }>
}) {
  const resolvedParams = await params
  console.log('#234 locale in layout:', resolvedParams.locale)
  const resolvedLocale = resolveLocale({ locale: resolvedParams.locale })
  const dir = getDirection(resolvedLocale)

  return (
    <html lang={resolvedLocale} dir={dir}>
      <head>
        <ThemeScript />
      </head>
      <body className="min-h-screen flex items-center justify-center bg-gray-50">
        {children}
      </body>
    </html>
  )
}
