import type { Metadata } from 'next'
// import { Geist, Geist_Mono } from 'next/font/google'
import { resolveLocale } from '@/lib/i18n/utils/resolve-locale'
import '@/app/globals.css'
import { ServerProviders } from '@/components/context/ServerProviders'
import { Toaster } from '@/components/ui/sonner'
import { ModeToggle } from '@/components/theme-mode-toggle/ModeToggle'
import { LocaleProvider } from '@/components/context/locale-provider'
import { Suspense } from 'react'
import { getSettingsAction } from '@/lib/features/settings/actions'
import { redirect } from 'next/navigation'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode
  params: Promise<{ locale: string }>
}
const Layout_ = async ({ children, params }: Props) => {
  const { locale } = await params
  console.log('#234 locale:', locale)
  const { resolvedLocale, dictionary, dir } = await resolveLocale({
    locale,
    scope: 'install',
  })
  return (
    <html lang={resolvedLocale} dir={dir}>
      <body>
        <ServerProviders locale={locale}>
          <main className=" ">
            <header className="p-2">
              <ModeToggle />
            </header>
            <LocaleProvider dictionary={dictionary}>{children}</LocaleProvider>
          </main>
        </ServerProviders>
        <Toaster />
      </body>
    </html>
  )
}

export default async function Layout({ children, params }: Props) {
  const settings = await getSettingsAction()
  if (settings.appInstalled) redirect('/')
  return (
    <Suspense fallback="loading auth layout...">
      <Layout_ params={params}>{children}</Layout_>
    </Suspense>
  )
}
