import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { resolveLocale } from '@/lib/i18n/utils/resolve-locale'
import '@/app/globals.css'
import { ServerProviders } from '@/components/context/ServerProviders'
import { getInstallDictionary } from '@/lib/i18n/install'
import { Toaster } from '@/components/ui/sonner'
import { getDirection } from '@/lib/i18n/utils/getDirection'
import { ModeToggle } from '@/components/theme-mode-toggle/ModeToggle'
import { LocaleProvider } from '@/components/context/locale-provider'
import { SupportedLanguage } from '@/lib/types'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode
  params: Promise<{ locale: string }>
}
export default async function Layout({ children, params }: Props) {
  const { locale } = await params
  console.log('#234 locale:', locale)
  const resolvedLocale = resolveLocale({ locale }) as SupportedLanguage
  const dictionary = getInstallDictionary(resolvedLocale)
  const dir = getDirection(resolvedLocale)
  return (
    <html lang={resolvedLocale} dir={dir}>
      <body>
        <ServerProviders>
          <main className=" ">
            <header className="p-2">
              <ModeToggle />
            </header>
            <LocaleProvider dictionary={dictionary}>{children}</LocaleProvider>
          </main>
        </ServerProviders>
        <Toaster />
      </body>
    </html>
  )
}
