import type { Metadata } from 'next'
import '@/app/globals.css'
import { getSettings } from '@/lib/features/settings/controller'
import { Settings } from '@/lib/features/settings/interface'
import { redirect } from 'next/navigation'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const siteSettings: Settings = (await getSettings()) as Settings
  if (siteSettings?.appInstalled == false) redirect('/install/language')
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  )
}
