import type { Metadata } from 'next'
import '@/app/globals.css'
import { getSettings } from '@/lib/features/settings/controller'
import { Settings } from '@/lib/features/settings/interface'
import { redirect } from 'next/navigation'
import { ThemeProvider } from '@/components/context/theme-provider'
import { DashboardLocaleProvider } from '@/components/context/dashboard-locale-provider'
import { getDashboardDictionary } from '@/lib/i18n/dashboard'
import { getSession } from '@/lib/auth/get-session'
import { Session, SupportedLanguage } from '@/lib/types'
import authorize from '@/lib/utils/authorize'
import { resolveLocale } from '@/lib/i18n/utils/resolve-locale'
import { SessionProvider } from '@/components/context/SessionContext'
import { Toaster } from '@/components/ui/sonner'

import localFont from 'next/font/local'

const iransans = localFont({
  src: [
    {
      path: '../../../public/fonts/IRANSansX-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/IRANSansX-Medium.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../../public/fonts/IRANSansX-DemiBold.woff2',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: '--font-iransans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const siteSettings: Settings = (await getSettings()) as Settings
  if (siteSettings?.appInstalled == false) redirect('/install/en/language')

  const session = (await getSession()) as Session
  const user = session?.user
  const haveDashboardAccess = authorize(user.roles, 'dashboard.view.any', false)
  if (!haveDashboardAccess) {
    redirect('/en/login')
  }
  const locale = user?.locale || siteSettings?.language?.dashboardDefault || ''
  const resolvedLocale = (await resolveLocale({ locale })) as SupportedLanguage
  const dictionary = getDashboardDictionary(resolvedLocale)
  const dir = dictionary.dir
  return (
    <html lang={resolvedLocale} dir={dir}>
      <body className={`antialiased ${iransans.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <DashboardLocaleProvider dictionary={dictionary}>
            <SessionProvider session={session}>{children}</SessionProvider>
            <Toaster />
          </DashboardLocaleProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
