import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { getDirection, resolveLocale } from '@/lib/i18n/resolve-locale'
import '@/app/globals.css'
import { SupportedLanguage } from '@/lib/types'
import { ServerProviders } from '@/components/context/ServerProviders'
import { getDictionary } from '@/lib/i18n'
import { Toaster } from '@/components/ui/sonner'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode
  params: Promise<{ locale?: SupportedLanguage }>
}
export default async function Layout({ children, params }: Props) {
  const resolvedParams = await params
  const resolvedLocale = resolveLocale({ locale: resolvedParams?.locale || '' })
  const dir = getDirection(resolvedLocale)
  return (
    <html lang={resolvedLocale} dir={dir}>
      <body>
        <ServerProviders>{children}</ServerProviders>
        <Toaster />
      </body>
    </html>
  )
}
