import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { getDirection, resolveLocale } from '@/lib/i18n/utils/resolve-locale'
import '@/app/globals.css'
import { SupportedLanguage } from '@/lib/types'
import { ServerProviders } from '@/components/context/ServerProviders'
import { getInstallDictionary } from '@/lib/i18n/install'
import { Toaster } from '@/components/ui/sonner'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode
  params: Promise<{ slugs: string[] }>
}
export default async function Layout({ children, params }: Props) {
  const resolvedParams = await params
  const locale = resolvedParams?.slugs?.[0] || ''
  console.log('#234 locale:', locale)
  const resolvedLocale = resolveLocale({ locale })
  const dictionary = getInstallDictionary(resolvedLocale)
  const dir = getDirection(resolvedLocale)
  return (
    <html lang={resolvedLocale} dir={dir}>
      <body>
        <ServerProviders dictionary={dictionary}>{children}</ServerProviders>
        <Toaster />
      </body>
    </html>
  )
}
