import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { getDirection, resolveLocale } from '@/lib/i18n/resolve-locale'
import '../../globals.css'
import { ReactNode } from 'react'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type LayoutProps = {
  children: ReactNode
}

export default function Layout({ children }: LayoutProps) {
  const resolvedLocale = resolveLocale({ locale: '' })
  const dir = getDirection(resolvedLocale)

  return (
    <html lang={resolvedLocale} dir={dir}>
      <body className="min-h-screen flex items-center justify-center bg-gray-50">
        {children}
      </body>
    </html>
  )
}
