import type { Metadata } from 'next'
// import { Geist, Geist_Mono } from 'next/font/google'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode
  params: Promise<{ slugs: string[] }>
}
export default async function Layout({ children, params }: Props) {
  return children
}
