// components/ui/TailwindClassInput/tailwind-classes.ts

export const TAILWIND_CLASSES: string[] = [
  // Layout
  'block',
  'inline',
  'inline-block',
  'flex',
  'inline-flex',
  'grid',
  'inline-grid',
  'hidden',

  // Flexbox
  'flex-row',
  'flex-col',
  'flex-wrap',
  'flex-nowrap',
  'items-start',
  'items-center',
  'items-end',
  'items-stretch',
  'justify-start',
  'justify-center',
  'justify-end',
  'justify-between',
  'justify-around',
  'justify-evenly',
  'gap-1',
  'gap-2',
  'gap-3',
  'gap-4',
  'gap-6',
  'gap-8',

  // Grid
  'grid-cols-1',
  'grid-cols-2',
  'grid-cols-3',
  'grid-cols-4',
  'grid-cols-6',
  'grid-cols-12',
  'col-span-1',
  'col-span-2',
  'col-span-3',
  'col-span-full',

  // Spacing - Padding
  'p-0',
  'p-1',
  'p-2',
  'p-3',
  'p-4',
  'p-5',
  'p-6',
  'p-8',
  'p-10',
  'p-12',
  'px-1',
  'px-2',
  'px-3',
  'px-4',
  'px-6',
  'px-8',
  'py-1',
  'py-2',
  'py-3',
  'py-4',
  'py-6',
  'py-8',
  'pt-1',
  'pt-2',
  'pt-4',
  'pt-6',
  'pt-8',
  'pb-1',
  'pb-2',
  'pb-4',
  'pb-6',
  'pb-8',
  'pl-1',
  'pl-2',
  'pl-4',
  'pr-1',
  'pr-2',
  'pr-4',

  // Spacing - Margin
  'm-0',
  'm-1',
  'm-2',
  'm-3',
  'm-4',
  'm-6',
  'm-8',
  'm-auto',
  'mx-1',
  'mx-2',
  'mx-4',
  'mx-auto',
  'my-1',
  'my-2',
  'my-4',
  'my-auto',
  'mt-1',
  'mt-2',
  'mt-4',
  'mt-6',
  'mt-8',
  'mb-1',
  'mb-2',
  'mb-4',
  'mb-6',
  'mb-8',
  'ml-1',
  'ml-2',
  'ml-4',
  'mr-1',
  'mr-2',
  'mr-4',

  // Sizing
  'w-full',
  'w-screen',
  'w-auto',
  'w-fit',
  'w-min',
  'w-max',
  'w-1/2',
  'w-1/3',
  'w-2/3',
  'w-1/4',
  'w-3/4',
  'w-4',
  'w-6',
  'w-8',
  'w-10',
  'w-12',
  'w-16',
  'w-20',
  'w-24',
  'w-32',
  'w-40',
  'w-48',
  'w-56',
  'w-64',
  'h-full',
  'h-screen',
  'h-auto',
  'h-fit',
  'h-4',
  'h-6',
  'h-8',
  'h-10',
  'h-12',
  'h-16',
  'h-20',
  'h-24',
  'h-32',
  'h-40',
  'h-48',
  'min-w-0',
  'min-w-full',
  'max-w-sm',
  'max-w-md',
  'max-w-lg',
  'max-w-xl',
  'max-w-2xl',
  'max-w-full',
  'min-h-0',
  'min-h-full',
  'min-h-screen',

  // Typography
  'text-xs',
  'text-sm',
  'text-base',
  'text-lg',
  'text-xl',
  'text-2xl',
  'text-3xl',
  'text-4xl',
  'text-5xl',
  'font-thin',
  'font-light',
  'font-normal',
  'font-medium',
  'font-semibold',
  'font-bold',
  'font-extrabold',
  'italic',
  'not-italic',
  'underline',
  'line-through',
  'no-underline',
  'text-left',
  'text-center',
  'text-right',
  'text-justify',
  'leading-none',
  'leading-tight',
  'leading-normal',
  'leading-loose',
  'tracking-tight',
  'tracking-normal',
  'tracking-wide',
  'truncate',
  'text-ellipsis',
  'whitespace-nowrap',
  'whitespace-pre',
  'uppercase',
  'lowercase',
  'capitalize',

  // Colors - Text
  'text-white',
  'text-black',
  'text-slate-50',
  'text-slate-100',
  'text-slate-200',
  'text-slate-300',
  'text-slate-400',
  'text-slate-500',
  'text-slate-600',
  'text-slate-700',
  'text-slate-800',
  'text-slate-900',
  'text-gray-50',
  'text-gray-100',
  'text-gray-200',
  'text-gray-300',
  'text-gray-400',
  'text-gray-500',
  'text-gray-600',
  'text-gray-700',
  'text-gray-800',
  'text-gray-900',
  'text-red-400',
  'text-red-500',
  'text-red-600',
  'text-red-700',
  'text-blue-400',
  'text-blue-500',
  'text-blue-600',
  'text-blue-700',
  'text-green-400',
  'text-green-500',
  'text-green-600',
  'text-green-700',
  'text-yellow-400',
  'text-yellow-500',
  'text-yellow-600',
  'text-purple-400',
  'text-purple-500',
  'text-purple-600',
  'text-pink-400',
  'text-pink-500',
  'text-pink-600',
  'text-indigo-400',
  'text-indigo-500',
  'text-indigo-600',
  'text-orange-400',
  'text-orange-500',
  'text-orange-600',

  // Colors - Background
  'bg-white',
  'bg-black',
  'bg-transparent',
  'bg-slate-50',
  'bg-slate-100',
  'bg-slate-200',
  'bg-slate-300',
  'bg-slate-400',
  'bg-slate-500',
  'bg-slate-600',
  'bg-slate-700',
  'bg-slate-800',
  'bg-slate-900',
  'bg-gray-50',
  'bg-gray-100',
  'bg-gray-200',
  'bg-gray-300',
  'bg-gray-400',
  'bg-gray-500',
  'bg-gray-600',
  'bg-gray-700',
  'bg-gray-800',
  'bg-gray-900',
  'bg-red-50',
  'bg-red-100',
  'bg-red-400',
  'bg-red-500',
  'bg-red-600',
  'bg-blue-50',
  'bg-blue-100',
  'bg-blue-400',
  'bg-blue-500',
  'bg-blue-600',
  'bg-green-50',
  'bg-green-100',
  'bg-green-400',
  'bg-green-500',
  'bg-green-600',
  'bg-yellow-50',
  'bg-yellow-100',
  'bg-yellow-400',
  'bg-yellow-500',
  'bg-purple-50',
  'bg-purple-100',
  'bg-purple-400',
  'bg-purple-500',
  'bg-indigo-50',
  'bg-indigo-100',
  'bg-indigo-400',
  'bg-indigo-500',
  'bg-orange-50',
  'bg-orange-100',
  'bg-orange-400',
  'bg-orange-500',

  // Colors - Border
  'border-white',
  'border-black',
  'border-transparent',
  'border-gray-100',
  'border-gray-200',
  'border-gray-300',
  'border-gray-400',
  'border-gray-500',
  'border-slate-200',
  'border-slate-300',
  'border-slate-400',
  'border-red-300',
  'border-red-400',
  'border-red-500',
  'border-blue-300',
  'border-blue-400',
  'border-blue-500',
  'border-green-300',
  'border-green-400',
  'border-green-500',

  // Border
  'border',
  'border-0',
  'border-2',
  'border-4',
  'border-8',
  'border-t',
  'border-b',
  'border-l',
  'border-r',
  'border-solid',
  'border-dashed',
  'border-dotted',
  'rounded',
  'rounded-sm',
  'rounded-md',
  'rounded-lg',
  'rounded-xl',
  'rounded-2xl',
  'rounded-3xl',
  'rounded-full',
  'rounded-none',

  // Shadow
  'shadow-sm',
  'shadow',
  'shadow-md',
  'shadow-lg',
  'shadow-xl',
  'shadow-2xl',
  'shadow-none',

  // Opacity
  'opacity-0',
  'opacity-25',
  'opacity-50',
  'opacity-75',
  'opacity-100',

  // Position
  'static',
  'fixed',
  'absolute',
  'relative',
  'sticky',
  'top-0',
  'top-auto',
  'top-full',
  'bottom-0',
  'bottom-auto',
  'bottom-full',
  'left-0',
  'left-auto',
  'right-0',
  'right-auto',
  'inset-0',
  'inset-auto',
  'inset-x-0',
  'inset-y-0',
  'z-0',
  'z-10',
  'z-20',
  'z-30',
  'z-40',
  'z-50',
  'z-auto',

  // Overflow
  'overflow-auto',
  'overflow-hidden',
  'overflow-scroll',
  'overflow-visible',
  'overflow-x-auto',
  'overflow-y-auto',
  'overflow-x-hidden',
  'overflow-y-hidden',

  // Display / Visibility
  'visible',
  'invisible',
  'sr-only',

  // Cursor
  'cursor-auto',
  'cursor-default',
  'cursor-pointer',
  'cursor-wait',
  'cursor-not-allowed',
  'cursor-move',

  // Pointer Events
  'pointer-events-none',
  'pointer-events-auto',

  // User Select
  'select-none',
  'select-text',
  'select-all',

  // Transitions
  'transition',
  'transition-all',
  'transition-colors',
  'transition-opacity',
  'transition-shadow',
  'transition-transform',
  'duration-75',
  'duration-100',
  'duration-150',
  'duration-200',
  'duration-300',
  'duration-500',
  'duration-700',
  'ease-linear',
  'ease-in',
  'ease-out',
  'ease-in-out',

  // Transform
  'scale-75',
  'scale-90',
  'scale-95',
  'scale-100',
  'scale-105',
  'scale-110',
  'rotate-0',
  'rotate-45',
  'rotate-90',
  'rotate-180',
  'translate-x-0',
  'translate-y-0',
  '-translate-y-1',
  '-translate-y-2',

  // Ring
  'ring',
  'ring-0',
  'ring-1',
  'ring-2',
  'ring-4',
  'ring-blue-500',
  'ring-red-500',
  'ring-green-500',
  'ring-offset-1',
  'ring-offset-2',

  // Outline
  'outline-none',
  'outline',
  'outline-2',

  // Object Fit
  'object-contain',
  'object-cover',
  'object-fill',
  'object-none',

  // Aspect Ratio
  'aspect-auto',
  'aspect-square',
  'aspect-video',

  // List
  'list-none',
  'list-disc',
  'list-decimal',
  'list-inside',
  'list-outside',

  // Table
  'table',
  'table-auto',
  'table-fixed',
  'border-collapse',
  'border-separate',

  // Responsive prefixes (به عنوان پیشنهاد)
  'sm:flex',
  'sm:hidden',
  'sm:block',
  'sm:grid',
  'md:flex',
  'md:hidden',
  'md:block',
  'md:grid',
  'lg:flex',
  'lg:hidden',
  'lg:block',
  'lg:grid',
  'xl:flex',
  'xl:hidden',
  'xl:block',

  // Hover / Focus (به عنوان پیشنهاد)
  'hover:opacity-80',
  'hover:opacity-90',
  'hover:bg-gray-100',
  'hover:bg-blue-600',
  'hover:bg-red-600',
  'hover:text-blue-600',
  'hover:text-white',
  'hover:shadow-md',
  'hover:shadow-lg',
  'hover:scale-105',
  'hover:underline',
  'focus:outline-none',
  'focus:ring-2',
  'focus:ring-blue-500',

  // Backdrop
  'backdrop-blur-sm',
  'backdrop-blur',
  'backdrop-blur-md',

  // Placeholder
  'placeholder-gray-400',
  'placeholder-gray-500',
]
